name: CI Pipeline Python

on:
  push:
    branches:
      - main
      - develop
      - feature/**
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["3.9", "3.11"]

    steps:
      - name: Baixar código
        uses: actions/checkout@v4

      - name: Configurar Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'

      - name: Instalar dependências
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest flake8

      - name: Executar Testes
        run: |
          pytest

      - name: Executar Linter (Flake8)
        run: |
          flake8 .